### ISSUE TITLE
About the rendering of G-objaverse

### ISSUE THREAD

**Issue by Amuseum-WHR** [modelscope/richdreamer#11]
Hello, I am interested in some details of G-Objaverse. Are you using environment map or area light while rendering for RGB images?

**Comment by X-skyer** [comment]
Yes, we use environment maps or area light with various color temperatures.

**Comment by X-skyer** [comment]
> Hello, I am interested in some details of G-Objaverse. Are you using environment map or area light while rendering for RGB images?


Yes, we use environment maps or area light with various color temperatures.

**Comment by Amuseum-WHR** [comment]
> > Hello, I am interested in some details of G-Objaverse. Are you using environment map or area light while rendering for RGB images?
> 
> Yes, we use environment maps or area light with various color temperatures.

thank you! And I have another question, you release 10 categories, including Human-Shape (41,557), Animals (28,882), Daily-Used (220,222), Furnitures (19,284), Buildings&&Outdoor (116,545), Transportations (20,075), Plants (7,195), Food (5,314), Electronics (13,252) and Poor-quality (107,001). However, the json file shows that for each category there are Human-Shape (10,334), Animals (12,549), Daily-Used (99,365), Furnitures (7,296), Buildings&&Outdoor (25,820), Transportations (8,925), Plants (3,337), Food (2,590), Electronics (6,255) and Poor-quality (31,775). And the total number is 20,8246. I wonder whether the number in README is wrong, or whether some data is missed in json file.

**Comment by fdyuandong** [comment]
Hi, a small part of the objaverse_280k rendering data that has been released lacks category annotations, and we are working hard to label this portion of the data. We will update the annotation files of all objaverse as soon as possible.

**Comment by Amuseum-WHR** [comment]
> Hi, a small part of the objaverse_280k rendering data that has been released lacks category annotations, and we are working hard to label this portion of the data. We will update the annotation files of all objaverse as soon as possible.

ok, thank you!
