### ISSUE TITLE
About dataset subset size

### ISSUE THREAD

**Issue by NIRVANALAN** [modelscope/richdreamer#13]
Hi, I am trying to use the "Furnitures" subset for experiments. As denoted in the README, this subset should contain 19,284 objects. However, the json (gobjaverse_280k_Furnitures.json) only has around 7296 items. I wonder whether the json is truncated or there are other issues? 

Thanks and looking forward to your reply.

**Comment by fdyuandong** [comment]
The current release of gobjaverse_280k is a subset of the objaverse (we calculated the CLIP scores between text and images, and selected this portion with high scores for training ND-MV and Albedo-MV). The download script currently provides only a specific category within gobjaverse_280k, so the available data will be less than what is mentioned in the README.

**Comment by NIRVANALAN** [comment]
I see, thanks Yuandong for your clarification!
