### ISSUE TITLE
GObjaverse Data seems to be broken

### ISSUE THREAD

**Issue by jinya1013** [modelscope/richdreamer#14]
Hello, thank you for amazing work and making GObjaverse dataset available!

I downloaded GObjaverse280k Food subset, but it seems that data in "76/394196" directory is broken. Could you if check they are in correct formats?

For instance, the content of downloaded `/76/394196/00000/00000_hdr.exr` is like

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>65AAF0EA7262F4393827FBF1</RequestId>
  <HostId>virutalbuy-public.oss-cn-hangzhou.aliyuncs.com</HostId>
  <Key>share/aigc3d/objaverse/76/394196/campos_512_v4/00000/00000_hdr.exr</Key>
  <EC>0026-00000001</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0026-00000001</RecommendDoc>
</Error>
```

**Comment by fdyuandong** [comment]
Hi, I have fixed the error, and you can try downloading again. If there are any other issues, please feel free to contact us.

**Comment by jinya1013** [comment]
Thanks for fixing the problem. By the way, as far as I have checked, at least the following further data out of GObjaverse-Food is broken as well. Could you check if they are in correct format as well? Thank you!

43/228784
97/498647
32/173761
25/138096
105/535617
76/394772
74/381967
159/808368
76/39063
49/259217
58/303560
49/258240
83/426609
77/395957
26/144683
133/675688
100/514172
117/599392
98/500316
109/558950/00027/00027.png
109/558950/00028/00028.png
109/558950/00029/00029.png
109/558950/00030/00030.png
109/558950/00031/00031.png
109/558950/00032/00032.png
109/558950/00033/00033.png
109/558950/00034/00034.png
109/558950/00035/00035.png
109/558950/00036/00036.png
109/558950/00037/00037.png
109/558950/00038/00038.png
109/558950/00039/00039.png
124/632632/00027/00027.png
124/632632/00028/00028.png
124/632632/00029/00029.png
124/632632/00030/00030.png
124/632632/00031/00031.png
124/632632/00032/00032.png
31/167934/00027/00027.png
31/167934/00028/00028.png
31/167934/00029/00029.png
31/167934/00030/00030.png
31/167934/00031/00031.png
31/167934/00032/00032.png
31/167934/00033/00033.png
31/167934/00034/00034.png
31/167934/00035/00035.png
31/167934/00036/00036.png
31/167934/00037/00037.png
31/167934/00038/00038.png
31/167934/00039/00039.png
37/197189/00027/00027.png
37/197189/00028/00028.png
37/197189/00029/00029.png

**Comment by hitsz-zuoqi** [comment]
> Thanks for fixing the problem. By the way, as far as I have checked, at least the following further data out of GObjaverse-Food is broken as well. Could you check if they are in correct format as well? Thank you!
> 
> 43/228784 97/498647 32/173761 25/138096 105/535617 76/394772 74/381967 159/808368 76/39063 49/259217 58/303560 49/258240 83/426609 77/395957 26/144683 133/675688 100/514172 117/599392 98/500316 109/558950/00027/00027.png 109/558950/00028/00028.png 109/558950/00029/00029.png 109/558950/00030/00030.png 109/558950/00031/00031.png 109/558950/00032/00032.png 109/558950/00033/00033.png 109/558950/00034/00034.png 109/558950/00035/00035.png 109/558950/00036/00036.png 109/558950/00037/00037.png 109/558950/00038/00038.png 109/558950/00039/00039.png 124/632632/00027/00027.png 124/632632/00028/00028.png 124/632632/00029/00029.png 124/632632/00030/00030.png 124/632632/00031/00031.png 124/632632/00032/00032.png 31/167934/00027/00027.png 31/167934/00028/00028.png 31/167934/00029/00029.png 31/167934/00030/00030.png 31/167934/00031/00031.png 31/167934/00032/00032.png 31/167934/00033/00033.png 31/167934/00034/00034.png 31/167934/00035/00035.png 31/167934/00036/00036.png 31/167934/00037/00037.png 31/167934/00038/00038.png 31/167934/00039/00039.png 37/197189/00027/00027.png 37/197189/00028/00028.png 37/197189/00029/00029.png

hey, some data starts from 00027.png because, in the second rendering round, we leave a little part(several objects).  And perhaps you could now debug your program using the downloaded files by checking whether it is completed, and skip the incomplete data in the dataloader. We are sorry for the missing files since it is uploaded distributedly and something unexpected has happened. We will check and upload the missing files soon, stay tuned!
