### ISSUE TITLE
Meet some problems when running the code

### ISSUE THREAD

**Issue by snowflakewang** [modelscope/richdreamer#15]
Hello, thank you for your brilliant work! I am deeply impressed by the results shown on the project page. Their geometry and texture are quite highly detailed!
But I have some problems when running the code. I think it is my reason. But I do not know which step is wrong.
I used _tools/download_nd_models.py_ to download the model checkpoint successfully. But when I ran the command:
```bash
prompt="A statue of angel, 3d asset"
out_path=outputs/$(echo "$prompt" | tr " " "_")

python run_dmtet.py -t "$prompt" -o "$out_path"
```
I got the following problems:
```
RuntimeError: Error(s) in loading state_dict for LatentDiffusionInterface:
        Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids".
```
Could you help me to fix it? Thanks a lot! :)

Update:
I change the following in _model_zoo.py_
```python
model.load_state_dict(model_ckpt, strict=False) # model.load_state_dict(model_ckpt, strict=strict)
```
Then the code can be run successfully. But I do not know whether this operation is true.

**Comment by lingtengqiu** [comment]
what is your diffusers version or transformers version?

**Comment by snowflakewang** [comment]
transformers==4.37.0.dev0
diffusers==0.23.0

**Comment by lingtengqiu** [comment]
try:
  diffusers==0.180 &
  transformers==4.30.2
