### ISSUE TITLE
How can I download these categories without duplicate objects?

### ISSUE THREAD

**Issue by thucz** [modelscope/richdreamer#19]
`Human-Shape (41,557), Animals (28,882), Daily-Used (220,222), Furnitures (19,284), Buildings&&Outdoor (116,545), Transportations (20,075), Plants (7,195), Food (5,314), Electronics (13,252) and Poor-quality (107,001).`

objaverse_280k should have only 280k. But these add up to much more than 280k objects. It seems these categories are not mutually exclusive. What categories should I download to avoid downloading duplicate objects?

**Comment by fdyuandong** [comment]
Hi, the current release of gobjaverse_280k is a subset of the objaverse (we calculated the CLIP scores between text and images, and selected this portion with high scores for training ND-MV and Albedo-MV). So the 'category_annotation.json' have more annotations than gobjaverse_280k. You can download the annotation for each category of gobjaverse_280k using 'wget https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/aigc3d/gobjaverse_280k_split/gobjaverse_280k_{category_name}.json'.

**Comment by thucz** [comment]
Thanks!
