### ISSUE TITLE
no scripts/dmtet/run_batch_fast.sh  in the repo

### ISSUE THREAD

**Issue by msocko420** [modelscope/richdreamer#2]
Hey there, I am still working through the repo and processes and realized there is no run batch fast for dmtet. I am still looking to understand better how the dmtet commands properly process a single text prompt. Thanks for all of your work!

**Comment by lingtengqiu** [comment]
Sorry, we will update ASAP

**Comment by gxd1994** [comment]
@msocko420  We upload it,  thank you.
