### ISSUE TITLE
How to directly transport data with OSS/rclone

### ISSUE THREAD

**Issue by NIRVANALAN** [modelscope/richdreamer#20]
Hi, I am also using Aliyun for experiments and wonder whether I can directly transfer data from your OSS to mine.

**Comment by NIRVANALAN** [comment]
e.g., the AK, SK

**Comment by fdyuandong** [comment]
Hi, due to data security concerns, I'm afraid we cannot share the Access Key with you. However, you can download the data using the provided script. Please feel free to contact us if you have any questions.

**Comment by NIRVANALAN** [comment]
Thank you for your response!
