### ISSUE TITLE
关于 用 Live-demo

### ISSUE THREAD

**Issue by swanilee** [modelscope/richdreamer#24]
首先, 很感谢这么优秀的研究.

如果 外国人 想用 live-demo 的话， 这么办啊?
我先做注册上网站，但是我没有中国手机号。
所以我不会进入 live-demo 。

请告诉我用 live-demo的 方法吗？  

谢谢

**Comment by gxd1994** [comment]
Thank you for your attention.
We will release a live demo in huggingface around April or May.

**Comment by gxd1994** [comment]
@swanilee 
live demo: https://modelscope.cn/studios/Damo_XR_Lab/3D_AIGC
You can log in to the site using your GitHub account.
