### ISSUE TITLE
Meaning of 00000_ng.exr in the Gobjaverse dataset?

### ISSUE THREAD

**Issue by Lizb6626** [modelscope/richdreamer#25]
Thank you for your outstanding work on the Gobjaverse dataset. 

While exploring the dataset, I came across a file named `00000_ng.exr` within the downloaded folder which is not mentioned in the readme. Could you please explain the purpose of the `00000_ng.exr` file? 

Also, I am encountering a minor issue when reading the `.exr` files. I use `cv2.imread(PATH_TO_EXR_FILE, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)` and obtain three channels. However, when opened in GIMP, they seem to have an additional alpha channel.

**Comment by lingtengqiu** [comment]
1. ng.exr is the ground truth normal map. on the other hand, nd.exr is the normal map adding bump to enhance the detail of geometry surface.
2. What is the version of opencv?

**Comment by Lizb6626** [comment]
The version of opencv is 4.9.0

```bash
>>> import os
>>> os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"
>>> import cv2
>>> img_nd = cv2.imread('00014_nd.exr', cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
>>> img_nd.shape
(512, 512, 3)
>>> img_hdr = cv2.imread('00014_hdr.exr', cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
>>> img_hdr.shape
(512, 512, 3)
>>> print(cv2.__version__)
4.9.0
```

**Comment by karimknaebel** [comment]
so is it generally recommended to use `nd` instead of `ng` for training a normal estimation model?
