### ISSUE TITLE
A problem about prompt

### ISSUE THREAD

**Issue by XiaokunSun** [modelscope/richdreamer#29]
Thanks for your nice work! 
I noticed that in the third stage of texture optimization the prompt is prefixed with the string "a DSLR photo of XXX", but some prompts already have this prefix string in front of them, which results in two identical prefixes in front of the prompt, like "a DSLR photo of a DSLR photo of XXX", will this make the result worse? Or is this harmless?

**Comment by hitsz-zuoqi** [comment]
Sorry for that. Prompt is critical for a text-to-3D sampling process, try to remove the duplicate prefix and it should produce better results~
