### ISSUE TITLE
How to normalize the disparity (or depth) to feed into VAE in RichDreamer?

### ISSUE THREAD

**Issue by thucz** [modelscope/richdreamer#3]
Hi! Since Monocular Depth Network provides a relative disparity. How do you normalize the disparity (or depth) to feed into VAE?

**Comment by lingtengqiu** [comment]
You can see the supplementary from [arxiv version](https://arxiv.org/abs/2311.16918.)
Instead of disparity which has very poor property, we use relative depth ( setting near and far plane) to feed into VAE

**Comment by thucz** [comment]
Thanks for your reply! But I still wonder what values you set the near and far planes for the predicted depth for Monocular Depth Network.  Could you give me a script of how you exactly process the predicted disparity of MiDaS on LAION datasets?

**Comment by lingtengqiu** [comment]
For the predicted depth from Midas, we normalize disparity ```(dis - min(dis)) / (max(dis) - min(dis))```, given a prompt "xxx".
On the other hand, when we finetune multi-view normal-depth diffusion model on objaverse, we transfer disparity domain to inverse depth domain, given a prompt "xxxx, 3D asset."

**Comment by thucz** [comment]
Thanks! I got it.
