### ISSUE TITLE
Support for CUDA version 11.7?

### ISSUE THREAD

**Issue by Colezwhy** [modelscope/richdreamer#30]
Thank you for your excellent work! 
But I wonder whether there will be environments for GPUs with CUDA version 11.7(e.g. RTX 3090)? I wanted to explore further with your great work. 
Thank you very much.

**Comment by lingtengqiu** [comment]
We do not provide conda/docker environment for specific CUDA version.
But you can `pip install` according to our requirments.txt. We think this process that may be not hard for u

**Comment by Colezwhy** [comment]
> We do not provide conda/docker environment for specific CUDA version. But you can `pip install` according to our requirments.txt. We think this process that may be not hard for u

Thank you, I will try.
