### ISSUE TITLE
Some random points in depth wrapping

### ISSUE THREAD

**Issue by irimsky** [modelscope/richdreamer#32]
Hello, your dataset is a great job and I am testing on it.
I have tried the [depth wrap script example](https://github.com/modelscope/richdreamer/blob/aa5a0266380f3e5c64bc65ff00491b639169ac7b/dataset/gobjaverse/depth_warp_example.py) you gave in repo. However I found when reprojecting, there are some random noisy points away from the original model just like the picture below:
<img width="953" alt="image" src="https://github.com/modelscope/richdreamer/assets/42032614/2d4997dc-6342-4bf8-a16a-319da24d4289">

I tried different models and different angels, and the I got the same result. I have no idea what causes this.

**Comment by irimsky** [comment]
I may find out the reason. I debugged by writing out the original uv coords of these random points, and found that they all belong to **the edge of model**. And their depth are all have a sharp descend like this:

<img width="714" alt="image" src="https://github.com/modelscope/richdreamer/assets/42032614/36b3efb7-9077-4f59-8636-d204c36b4a08">

<img width="585" alt="image" src="https://github.com/modelscope/richdreamer/assets/42032614/b64caf12-05cc-4a04-bad7-05e0c1bcba5d">

Did you ever do any anti-aliasing on your normal and depth data?

**Comment by lingtengqiu** [comment]
Hi,
The error is caused by single-direction projection. you can smooth the projection error with a high-freq filter.

**Comment by irimsky** [comment]
what is 'single-direction projection' ?  And I am trying to get the 3d coordinates of these points. A simple filtering cannot solve this 3d random points.

**Comment by yjb6** [comment]
I found the same problem here, do you get any good solutions? thanks [#51]

**Comment by irimsky** [comment]
> I found the same problem here, do you get any good solutions? thanks [#51]

Not yet. I have found another similar dataset called Cap3D
