### ISSUE TITLE
The mapping between `instance_id` and  `uid` in objaverse dataset.

### ISSUE THREAD

**Issue by AImind** [modelscope/richdreamer#33]
Thanks for your wonderful work!
I want to filter some objects, while I don't know the relation of instance_id and objaverse uid. Could you please provide a mapping table about these?

**Comment by lingtengqiu** [comment]
Please download mapping-json file attached to Objaverse.
```python
wget https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/aigc3d/gobjaverse_280k_index_to_objaverse.json
```
