### ISSUE TITLE
What is the range of camera distance in g-objaverse? 

### ISSUE THREAD

**Issue by LiyingCV** [modelscope/richdreamer#34]
Hi, what is the range of camera distance and camera heights in g-objaverse? By the way, before rendering g-objaverse, do you normalize each 3D model into a unit cube in the range of [-1, 1] or [-0.5, 0.5]? Thanks in advance.

**Comment by lingtengqiu** [comment]
The 3D model is normalized into a cube whose range is [-0.5,0.5]; we randomly sample camera distance from the specific range [1.0, 1.5];  the height is dependent on sampling elevation~(15 or -15 degrees.)

**Comment by LiyingCV** [comment]
> The 3D model is normalized into a cube whose range is [-0.5,0.5]; we randomly sample camera distance from the specific range [1.0, 1.5]; the height is dependent on sampling elevation~(15 or -15 degrees.)

Thanks!
