### ISSUE TITLE
如何生成法线图

### ISSUE THREAD

**Issue by zhou431496** [modelscope/richdreamer#35]
请问在生成数据集时，法线图是如何获取的，是通过Omnidata嘛

**Comment by lingtengqiu** [comment]
生成数据集，是指laion 的pretrain 阶段吗？

**Comment by zhou431496** [comment]
> 生成数据集，是指laion 的pretrain 阶段吗？

是的，这个过程需要法线图，深度图这些。我在生成法线图时Omnidata方法生成的质量很低，我发现这篇论文生成法线质量很高，所以我想知道你们用了什么方法，有相关代码可以提供嘛。

**Comment by lingtengqiu** [comment]
我这里Normal 用的是NormalBAE，depth 用的是Midas3.2； 当前有更好的Normal 估计器如DSINE，你可以尝试使用下。 而且数据的处理，size 也很重要，这些你要自己去试一试
