### ISSUE TITLE
the code for the rendering RGB images

### ISSUE THREAD

**Issue by runzeer** [modelscope/richdreamer#37]
Could you share the source codes about the rendering RGB images ?

**Comment by lingtengqiu** [comment]
do you indicate the rendering code for G-objaverse or generated objects?

**Comment by runzeer** [comment]
Yes. I noticed that the G-objaverse is rendered useing the TIDE. If convenient, could you share the rendering code about the Blender python script?

**Comment by lingtengqiu** [comment]
Sorry, the code for rendering G-objaverse cannot be shared due to some reasons- -.
