### ISSUE TITLE
Why do we get different results after fixing the random seed?

### ISSUE THREAD

**Issue by DaLi-Jack** [modelscope/richdreamer#39]
Thanks for your great work! But we get different results after fixing the random seed, two experiment results are as follows:
1.the first result
![it001500-0030](https://github.com/modelscope/richdreamer/assets/70205757/fd1ccaba-9cfc-4412-aae1-9cbd1d944d04)
2.the second result
![it001500-0030-1](https://github.com/modelscope/richdreamer/assets/70205757/934396f2-2e43-429e-949a-3c851b1a7493)
I have fixed the seed in your configs.
Looking forward for your reply!

**Comment by lingtengqiu** [comment]
I guess the threestudio framework in the previous version caused it.
