### ISSUE TITLE
How to download a subset dataset with a specific category?

### ISSUE THREAD

**Issue by thucz** [modelscope/richdreamer#4]

**Comment by fdyuandong** [comment]
We will provide the download script soon.

**Comment by thucz** [comment]
Thanks a lot!

**Comment by QuLiao1117** [comment]
When will this script be released? Thanks

**Comment by thucz** [comment]
> When will this script be released? Thanks

The script has been released. See the readme.md in https://github.com/modelscope/richdreamer/tree/main/dataset/gobjaverse
