### ISSUE TITLE
Question about Input Data Choices for Stable Diffusion in DMTet and NeRF Methods

### ISSUE THREAD

**Issue by DaLi-Jack** [modelscope/richdreamer#40]
Hi! Great work!
However, I have a question. Why is the normal map used as input for the stable diffusion model in the DMTet-based method, while the RGB map is used in the NeRF-based method? Is there a specific reason for this?
Looking forward to your response!

**Comment by lingtengqiu** [comment]
For NeRF, since the initial normal map produced by NeRF is not as good as the one generated by DMTet, we use a different approach. Specifically, we use an RGB map as the initial input for Stable Diffusion. After achieving stable training, we switch to using the normal.

**Comment by DaLi-Jack** [comment]
Thank you for your reply, it has resolved my problem!
