### ISSUE TITLE
which channels are metallic and roughness in xxxxx_mr.png

### ISSUE THREAD

**Issue by Binyr** [modelscope/richdreamer#41]
Hi, thanks for your great work!

I notice that gobjaverse contains metallic and roughness in "xxxxx_mr.png". But this png has 4 channels, which channels corresponds to metallic and roughness?

Thank you,
Yanrui

**Comment by lingtengqiu** [comment]
Yes, The first channel denotes metallic while the second one means roughness. The remain channels are zeros.
