### ISSUE TITLE
G-Objaverse Rendering Code

### ISSUE THREAD

**Issue by chenguolin** [modelscope/richdreamer#42]
Hi, thank you for releasing the G-Objaverse dataset. It is a great job!

I noticed that G-Objaverse is rendered by a renderer named TIDE. Is TIDE open-source? Can we use it to render Objaverse samples in our own settings?

Also, do you have any tips on how to render roughness and metallic images in Blender or TIDE like in G-Objaverse?

Thank you very much!

**Comment by gxd1994** [comment]
@chenguolin 
Sorry, TIDE is our own product and not open source. If you have any questions, please contact our professionals (eric.xc@alibaba-inc.com)
