### ISSUE TITLE
How to get the Objaverse UID for G-Objaverse-XL?

### ISSUE THREAD

**Issue by chenguolin** [modelscope/richdreamer#43]
The file name in `gobjaverse_alignment.json` differs from the keys in `gobjaverse_index_to_objaverse.json`. Then how can we obtain the Objaverse uid of G-Objaverse-XL renderings?

Thank you very much.

**Comment by AndreAmaduzzi** [comment]
+1

**Comment by lingtengqiu** [comment]
I will clean a list for gobjaverse-id to xl-download hash mapping.

**Comment by HochCC** [comment]
+1

**Comment by yosefdayani** [comment]
+1

**Comment by 834810269** [comment]
> I will clean a list for gobjaverse-id to xl-download hash mapping.

Hello, is there any update on this?

**Comment by NIRVANALAN** [comment]
Hi, any progress on this? Thanks for your help!

**Comment by aplatyps** [comment]
Can the Objaverse uid of G-Objaverse-XL renderings and the catergories lists be released to public please 🥺🙏

**Comment by fdyuandong** [comment]
We have released the Mapping File of G-Objaverse-XL, and you can also find other information, such as the license, SHA256, and metadata, in 'alignment.parquet.' (https://colab.research.google.com/drive/15XpZMjrHXuky0IgBbXcsUtb_0g-XWYmN?usp=sharing#scrollTo=4S_yqHYLAz8p).

**Comment by ErrorLogic1211** [comment]
I tried to make alignment between the JSON files (obj , ply, etc... )you provided and the ObjaverseXL annotation dataframe. I ended up with 438855 matches only. Here is the code:

```python
import objaverse
import objaverse.xl as oxl

annotations = oxl.get_annotations(
    download_dir=r"~\objaverse" # default download directory
)

import json
import pandas as pd
# Load the JSON files
with open('sketchfab_map.json') as f:
    sketchfab_map = json.load(f)
with open('glb_map.json') as f:
    glb_map = json.load(f)
with open('fbx_map.json') as f:
    fbx_map = json.load(f)
with open('obj_map.json') as f:
    obj_map = json.load(f)


# # Convert the list of dictionaries to a single dictionary
sketchfab_map = {k: v for d in sketchfab_map for k, v in d.items()}
glb_map = {k: v for d in glb_map for k, v in d.items()}
fbx_map = {k: v for d in fbx_map for k, v in d.items()}
obj_map = {k: v for d in obj_map for k, v in d.items()}

new_json = {}

# Function to update the new_json dictionary
def update_new_json(data_map):
    # Pre-filter annotations and create a dictionary for faster lookup
    sha256_dict = dict(zip(annotations['fileIdentifier'].astype(str), annotations['sha256']))
    
    # Process in batches for better performance
    batch_size = 10000
    items = list(data_map.items())
    
    for i in range(0, len(items), batch_size):
        batch = items[i:i + batch_size]
        for key, value in batch:
            if str(value) in sha256_dict:
                new_json[str(key).split('.')[0]] = sha256_dict[str(value)]
        print(f"Processed {i + len(batch)} items")

# # Update the new_json dictionary with values from each JSON file
update_new_json(sketchfab_map)
update_new_json(glb_map)
update_new_json(fbx_map)
update_new_json(obj_map)
with open('new_json_file.json', 'w') as f:
    json.dump(new_json, f, indent=4)
```

**Comment by ZX-Yin** [comment]
> I tried to make alignment between the JSON files (obj , ply, etc... )you provided and the ObjaverseXL annotation dataframe. I ended up with 438855 matches only. Here is the code:
> 
> import objaverse
> import objaverse.xl as oxl
> 
> annotations = oxl.get_annotations(
>     download_dir=r"~\objaverse" # default download directory
> )
> 
> import json
> import pandas as pd
> # Load the JSON files
> with open('sketchfab_map.json') as f:
>     sketchfab_map = json.load(f)
> with open('glb_map.json') as f:
>     glb_map = json.load(f)
> with open('fbx_map.json') as f:
>     fbx_map = json.load(f)
> with open('obj_map.json') as f:
>     obj_map = json.load(f)
> 
> 
> # # Convert the list of dictionaries to a single dictionary
> sketchfab_map = {k: v for d in sketchfab_map for k, v in d.items()}
> glb_map = {k: v for d in glb_map for k, v in d.items()}
> fbx_map = {k: v for d in fbx_map for k, v in d.items()}
> obj_map = {k: v for d in obj_map for k, v in d.items()}
> 
> new_json = {}
> 
> # Function to update the new_json dictionary
> def update_new_json(data_map):
>     # Pre-filter annotations and create a dictionary for faster lookup
>     sha256_dict = dict(zip(annotations['fileIdentifier'].astype(str), annotations['sha256']))
>     
>     # Process in batches for better performance
>     batch_size = 10000
>     items = list(data_map.items())
>     
>     for i in range(0, len(items), batch_size):
>         batch = items[i:i + batch_size]
>         for key, value in batch:
>             if str(value) in sha256_dict:
>                 new_json[str(key).split('.')[0]] = sha256_dict[str(value)]
>         print(f"Processed {i + len(batch)} items")
> 
> # # Update the new_json dictionary with values from each JSON file
> update_new_json(sketchfab_map)
> update_new_json(glb_map)
> update_new_json(fbx_map)
> update_new_json(obj_map)
> with open('new_json_file.json', 'w') as f:
>     json.dump(new_json, f, indent=4)

@ErrorLogic1211 Hi, thanks for your script. I find that all the mismatches are in the sketchfab_map.json. You can simply change the line 
``` sketchfab_map = {k: v for d in sketchfab_map for k, v in d.items()} ```
to 
``` sketchfab_map = {k: v[:32] + v[32:].split('-')[-1] for d in sketchfab_map for k, v in d.items()} ``` to fix the problem.

@lingtengqiu Hi, thanks for this wonderful work. In the mapping file ```sketchfab_map.json``` of Objaverse-XL, the urls are not aligned with those from the official tools. In the json file ```sketchfab_map.json```, the urls are ```https://sketchfab.com/3d-models/aaa-bbbbbb" but in the official tools they are "https://sketchfab.com/3d-models/bbbbbb", and I have checked some samples, the urls in above two formats lead to the same 3D models. Perhaps you could further check it and update the mapping json file.
