### ISSUE TITLE
How to use this model to do novel view synthesize?

### ISSUE THREAD

**Issue by LaFeuilleMorte** [modelscope/richdreamer#44]
Hi, I was trying to find a model to generate novel views conditioned on an image/ text prompt given a camera pose. I don't need the reconstruction pipeline. Does this work for me?  Thanks in advance!

**Comment by gxd1994** [comment]
@LaFeuilleMorte 
You can use our model to generate a 3D mesh model by inputting a text prompt, and then render a novel view with this 3D model.
