### ISSUE TITLE
Can this ND diffusion be applied to Gaussian Splatting scenarios?

### ISSUE THREAD

**Issue by Colezwhy** [modelscope/richdreamer#46]
Hi, thank you very much for your great work.
But I am now wondering whether the Normal-depth diffusion model can be directly applied to Gaussian Splatting systems and function?

**Comment by lingtengqiu** [comment]
Do you mean you wanna use the diffusion model to estimate normal or depth which supervises the normal/depth map of gaussian ?

**Comment by Colezwhy** [comment]
> Do you mean you wanna use the diffusion model to estimate normal or depth which supervises the normal/depth map of gaussian ?

Yes, is that possible?

**Comment by lingtengqiu** [comment]
For this case, a possible solution is training a image-condition diffusion model to predict normal/depth, like, [Marigold](https://github.com/prs-eth/Marigold), [Genpercept](https://github.com/aim-uofa/GenPercept) or [GeoWizard](https://github.com/fuxiao0719/GeoWizard).

**Comment by Colezwhy** [comment]
> For this case, a possible solution is training a image-condition diffusion model to predict normal/depth, like, [Marigold](https://github.com/prs-eth/Marigold), [Genpercept](https://github.com/aim-uofa/GenPercept) or [GeoWizard](https://github.com/fuxiao0719/GeoWizard).

So in this case, the ND diffusion proposed in RichDreamer can not be directly applied?
Thank you for your kind reply.

**Comment by lingtengqiu** [comment]
Yes, our normal-depth diffusion is text-to-nd; for your setting, it is img-to-nd

**Comment by Colezwhy** [comment]
> Yes, our normal-depth diffusion is text-to-nd; for your setting, it is img-to-nd

Thanks, closing this issue.

**Comment by lingtengqiu** [comment]
> > Yes, our normal-depth diffusion is text-to-nd; for your setting, it is img-to-nd
> 
> Thanks, closing this issue.

Or you can use our new normal estiamtion method： StableNormal got accepted by Siggraph-Asia 2024, https://huggingface.co/Stable-X/stable-normal-v0-1/tree/main

**Comment by Colezwhy** [comment]
> > > Yes, our normal-depth diffusion is text-to-nd; for your setting, it is img-to-nd
> > 
> > 
> > Thanks, closing this issue.
> 
> Or you can use our new normal estiamtion method： StableNormal got accepted by Siggraph-Asia 2024, https://huggingface.co/Stable-X/stable-normal-v0-1/tree/main

Wow, great job! Thank you for the info!
