### ISSUE TITLE
G-Obj dataset depth value range?

### ISSUE THREAD

**Issue by insomniaaac** [modelscope/richdreamer#48]
thx for opening such great dataset.
when i use depth map, i can not figure out the range of depth value.
```python
nd = cv2.imdecode(nd, cv2.IMREAD_UNCHANGED).astype(
                    np.float32
                )  # [512, 512, 4] in [-1, 1]
normal = nd[..., :3]  # in [-1, 1], bg is [0, 0, 1]
depth = nd[..., 3]  # in [0, +?), bg is 0
```

**Comment by lingtengqiu** [comment]
the depth value indicates that abs distance between camera near plane to obj. Notably, the background we set to 0 in depth map.

**Comment by insomniaaac** [comment]
thanks for quick response. however, i still confuse about the znear and zfar value when obj rendered.

**Comment by lingtengqiu** [comment]
Hi the camera znear  is set to 0.01 and zfar is set to 1000.
