### ISSUE TITLE
How large is the dataset (RGB-normal-depth, poses)? 

### ISSUE THREAD

**Issue by thucz** [modelscope/richdreamer#5]
I want to download the dataset but maybe have enough space storage. I want to know if I want to download the pose, RGB-normal-depth. How much space is needed?

**Comment by fdyuandong** [comment]
If you download only the RGB and Normal-Depth images, each object will require about 10MB of storage space. Therefore, downloading a subset of Objaverse (about 280,000 objects) would necessitate at least 3TB of storage space.

**Comment by thucz** [comment]
Thanks1
