### ISSUE TITLE
Kind inquiry about G-Objaverse-280k

### ISSUE THREAD

**Issue by Moondok** [modelscope/richdreamer#50]
Thanks for the high-quality dataset!

I wonder whether the dataset G-Objaverse-280k contains the category of "Poor-quality", and what is the criterion for “poor quality”, the quality of the mesh or the quality of the rendering?

**Comment by lingtengqiu** [comment]
Honestly,  the poor quality of mesh is hard to defined. We do not manually filter "low quality" mesh, but employ a simple strategy that filters boxes, ball, and some very simple obj.

**Comment by Moondok** [comment]
> Honestly, the poor quality of mesh is hard to defined. We do not manually filter "low quality" mesh, but employ a simple strategy that filters boxes, ball, and some very simple obj.

Got it! Thanks for your reply！
