### ISSUE TITLE
Cannot access to docker image

### ISSUE THREAD

**Issue by zh4men9** [modelscope/richdreamer#6]
hi, 

I cannot access to your docker image url: https://code.alibaba-inc.com/dadong.gxd/dream3d/blob/release/1209

please provide another one, thanks!

**Comment by HigherOrderGames** [comment]
I have the same problem.

**Comment by gxd1994** [comment]
@zh4men9 @HigherOrderGames  
We have released the built docker image and updated the README file,
 you can try:
```bash
sudo docker pull registry.cn-hangzhou.aliyuncs.com/ailab-public/aigc3d
```
