### ISSUE TITLE
configs/gradio not found

### ISSUE THREAD

**Issue by zh4men9** [modelscope/richdreamer#8]
hi,

I am running gradio_app.py, which needs "configs/gradio" config files, but I cannot find them in your project. Can you provide them for me, thanks!

**Comment by lingtengqiu** [comment]
We will push gradio api demo， ASAP

**Comment by zh4men9** [comment]
> We will push gradio api demo， ASAP

Thanks!

**Comment by zh4men9** [comment]
I want to deploy a web like your "Live Demo" (https://modelscope.cn/studios/Damo_XR_Lab/3D_AIGC) in my ubuntu20.02 machine. Can you provide a tutorial about how to do it, please. Thanks!

**Comment by lingtengqiu** [comment]
> I want to deploy a web like your "Live Demo" (https://modelscope.cn/studios/Damo_XR_Lab/3D_AIGC) in my ubuntu20.02 machine. Can you provide a tutorial about how to do it, please. Thanks!

This is our alibaba internal deployment platform, this you should not be able to deploy (●'◡'●)
